<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>SalsaNOW.Tests</RootNamespace>
    <AssemblyName>SalsaNOW.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SalsaNOW\SalsaNOW.csproj" />
  </ItemGroup>
</Project>
